### local imports

from ...fontsman.constants import ENC_SANS_BOLD_FONT_HEIGHT

from ..socket.surfs import SOCKET_DIAMETER


NODE_OUTLINE_THICKNESS = 2

SOCKET_X_PADDING = SOCKET_DIAMETER // 2

LABEL_X_PADDING = SOCKET_X_PADDING + 4

HEADER_LABEL_WIDTH_INCREMENT = LABEL_X_PADDING * 2

WIDGET_BUTTON_HEIGHT = 16

FONT_HEIGHT = ENC_SANS_BOLD_FONT_HEIGHT

HEADER_HEIGHT = FONT_HEIGHT + (2 * NODE_OUTLINE_THICKNESS) + 4

MAX_WIDTH = 155 - (2 * NODE_OUTLINE_THICKNESS) - 4
